{
 "title": "Kubernetes Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cluster_name)(up{cluster_name=~\".+\"}))"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster_name=~\".+\",job=~\".*cadvisor.*\"})"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",cluster_name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster_name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Pod capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster_name=~\".+\",unit=\"integer\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster_name=~\".+\"}) / sum(kube_node_status_capacity{cluster_name=~\".+\",unit=\"integer\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=~\".+\"}[1m])) / sum(kube_node_status_allocatable{cluster_name=~\".+\",resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=~\".+\"}) / sum(kube_node_status_allocatable{resource=\"memory\", cluster_name=~\".+\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster_name=~\".+\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{cluster_name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(count by(cluster_name)(max by(node, cluster_name)(up{cluster_name=~\".+\", job=~\".*cadvisor.*\"}) == 1)) or ((count by(cluster_name)(up{cluster_name=~\".+\", job=~\".*cadvisor.*\"}) * 0))"
    },
    {
     "expr": "(count by(cluster_name)(max by(instance_name,cluster_name)(up{cluster_name=~\".+\"}) == 0)) or ((count by(cluster_name)(up{cluster_name=~\".+\"}) * 0))"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster_name=~\".+\",resource=\"cpu\"}) by (cluster_name)"
    },
    {
     "expr": "sum by(cluster_name)(kube_pod_container_resource_requests{resource=\"cpu\"})"
    },
    {
     "expr": "sum by(cluster_name)(rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=~\".+\"}[1m])) / sum by(cluster_name)((kube_node_status_allocatable{resource=\"cpu\",cluster_name=~\".+\"})) * 100"
    },
    {
     "expr": "sum by(cluster_name)(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum by(cluster_name)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster_name=~\".+\",resource=\"memory\"}) by (cluster_name)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (cluster_name)"
    },
    {
     "expr": "sum by(cluster_name)((container_memory_working_set_bytes{image!=\"\",cluster_name=~\".+\"})) / sum by(cluster_name)(kube_node_status_allocatable{resource=\"memory\",cluster_name=~\".+\"}) * 100"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (cluster_name) / sum(kube_node_status_allocatable{resource=\"memory\"}) by (cluster_name)"
    },
    {
     "expr": "sum(kube_pod_info) by (cluster_name)"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) by (cluster_name)"
    },
    {
     "expr": "sum(kube_pod_info) by (cluster_name) / sum(kube_node_status_capacity{resource=\"pods\"}) by (cluster_name)"
    },
    {
     "expr": "sum by(cluster_name)((container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",cluster_name=~\".+\"})) / sum by(cluster_name)((container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\", cluster_name=~\".+\"})) * 100"
    },
    {
     "expr": "sum by(cluster_name)((rate (container_network_receive_bytes_total{cluster_name=~\".+\"}[1m])))"
    },
    {
     "expr": "sum by(cluster_name)((rate (container_network_transmit_bytes_total{cluster_name=~\".+\"}[1m])))"
    },
    {
     "expr": "max by (cluster_name,kubelet_version)(kube_node_info{cluster_name=~\".+\"})"
    }
   ]
  }
 ]
}