{
 "title": "Kubernetes Deployment",
 "description": "Dashboard for Kubernetes deployment with Prometheus.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_name=\"$cluster_name\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_service_labels{cluster_name=\"$cluster_name\",namespace=~\"^$namespace\"}, service)"
    }
   },
   {
    "name": "hpa",
    "label": "HPA",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}, horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( kube_deployment_status_replicas_available{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",deployment=~\".*$deployment.*\"} )"
    }
   ]
  },
  {
   "title": "Total Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Deployment Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max(kube_deployment_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",deployment=~\"$deployment\"}) by (deployment,namespace)"
    }
   ]
  },
  {
   "title": "Services Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "max(kube_service_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",service=~\"$service\"}) by (service,namespace)"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage by Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"}[1m])) / sum (kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage by Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"}) / sum (kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage Summary ( 1m avg )",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",container!=\"\",pod=~\".*$deployment.*\"}[1m])) by(namespace) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",resource=\"cpu\",pod=~\".*$deployment.*\"}) by(namespace)) * 100",
     "legendFormat": "REQUEST - {{ namespace }}"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",container!=\"\",pod=~\".*$deployment.*\"}[1m])) by(namespace) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"}) by(namespace)) * 100",
     "legendFormat": "LIMIT - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Deployment Memory Usage $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"}) by(namespace) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"}) by(namespace)",
     "legendFormat": "REQUEST - {{namespace}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\"}) by(namespace) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"}) by(namespace)",
     "legendFormat": "LIMIT -  {{namespace}}"
    }
   ]
  },
  {
   "title": "Pods CPU (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",container!=\"\"}[1m])) by (pod,container)",
     "legendFormat": "{{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"cpu\"}) by (pod,container)",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "Pods Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",container!=\"\"}) by (pod,container)",
     "legendFormat": "{{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\".*$deployment.*\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  { "title": "HPA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Autoscale Summary $namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "max (kube_horizontalpodautoscaler_spec_target_metric{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (horizontalpodautoscaler,metric_name,metric_target_type)"
    },
    {
     "expr": "max (kube_horizontalpodautoscaler_status_current_replicas{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (horizontalpodautoscaler)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_horizontalpodautoscaler_status_desired_replicas{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (horizontalpodautoscaler)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_horizontalpodautoscaler_spec_min_replicas{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (horizontalpodautoscaler)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_horizontalpodautoscaler_spec_max_replicas{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (horizontalpodautoscaler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"$hpa\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Replicas $hpa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(nginx_ingress_controller_requests{cluster_name=\"$cluster_name\",exported_namespace=~\"$namespace\",service=~\"$service\"}[30s]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster_name=\"$cluster_name\",\n        exported_namespace =~ \"$namespace\",\n        service =~ \"$service\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster_name=\"$cluster_name\",\n        exported_namespace =~ \"$namespace\",\n        service =~ \"$service\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster_name=\"$cluster_name\",\n        exported_namespace =~ \"$namespace\",\n        service =~ \"$service\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster_name=\"$cluster_name\",\n        exported_namespace =~ \"$namespace\",\n        service =~ \"$service\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_replace(increase(nginx_ingress_controller_requests{status=~\"[45].*\",cluster_name=\"$cluster_name\",exported_namespace=~\"$namespace\",service=~\"$service\"}[30s]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) by (status_code) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_replace(increase(nginx_ingress_controller_requests{status=~\"[2].*\",cluster_name=\"$cluster_name\",exported_namespace=~\"$namespace\",service=~\"$service\"}[30s]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) by (status_code) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}