{
 "title": "Kubernetes Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{ },cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "up{ job=~\".*cadvisor\",cluster_name=\"$cluster_name\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\".*cadvisor.*\",cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"}[1m])) / sum(kube_node_status_allocatable{cluster_name=\"$cluster_name\",resource=\"cpu\",node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"}) / sum(kube_node_status_allocatable{cluster_name=\"$cluster_name\",resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\",cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "PVC Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster_name=\"$cluster_name\",node=~\"$node\"}) /  sum(kube_node_status_capacity{resource=\"pods\",cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(node,node_ip,instance_project)(up{job=~\".*cadvisor\",cluster_name=\"$cluster_name\"})"
    },
    {
     "expr": "max by(node)(time() - container_start_time_seconds{cluster_name=\"$cluster_name\"})"
    },
    {
     "expr": "max by (node,kubelet_version)(kube_node_info{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "CPU Usages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Usages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"}[1m])) / sum(kube_node_status_capacity{cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Request utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"}) /  sum(kube_node_status_capacity{cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Usage Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",node=~\"$node\"}) / sum(kube_node_status_capacity{cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Request utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"memory\"}) /  sum(kube_node_status_capacity{cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  { "title": "Persistent Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Claim",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cluster_name,persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{cluster_name=~\"$cluster_name\"}))"
    }
   ]
  },
  {
   "title": "Total PVC Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total PVC Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total PVC Usages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster_name=\"$cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PVC Usages (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_used_bytes{}) / sum(kubelet_volume_stats_capacity_bytes{cluster_name=\"$cluster_name\"})) * 100"
    }
   ]
  },
  {
   "title": "PV Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (cluster_name,persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{cluster_name=\"$cluster_name\"})"
    },
    {
     "expr": "sum by (cluster_name,persistentvolumeclaim)(kubelet_volume_stats_available_bytes{cluster_name=\"$cluster_name\"})"
    },
    {
     "expr": "sum by (cluster_name,persistentvolumeclaim)(kubelet_volume_stats_used_bytes{cluster_name=\"$cluster_name\"})"
    },
    {
     "expr": "sum by (cluster_name,persistentvolumeclaim)(kubelet_volume_stats_used_bytes{cluster_name=\"$cluster_name\"}) / sum by (cluster_name,persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{cluster_name=\"$cluster_name\"}) * 100"
    }
   ]
  },
  { "title": "Object Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Statefulset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Daemonset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_service_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total Configmap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_configmap_labels{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Pods Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Deployments Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Statefulset Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_statefulset_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Daemonsets Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Services Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_service_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Configmaps Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "max(kube_node_info{cluster_name=\"$cluster_name\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_configmap_labels{cluster_name=\"$cluster_name\"}) by (namespace)"
    }
   ]
  },
  { "title": "Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}[1m])) by (node) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"}) by (node)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"}) by (node)/  sum(kube_node_status_allocatable{job=\"kube-state-metrics\",cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}} - Request"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(node)((container_memory_working_set_bytes{job=~\".*cadvisor\",id=\"/\",cluster_name=\"$cluster_name\",node=~\"$node\"}))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum by(node)((machine_memory_bytes{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}))",
     "legendFormat": "{{node}} - max"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"memory\"}) by (node)",
     "legendFormat": "{{node}} - request"
    }
   ]
  },
  {
   "title": "Memory (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node)((container_memory_working_set_bytes{job=~\".*cadvisor\",id=\"/\",cluster_name=\"$cluster_name\",node=~\"$node\"})) / sum by(node)((kube_node_status_allocatable{job=~\"kube-state-metrics\",cluster_name=\"$cluster_name\",node=~\"$node\",resource=\"memory\"}))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",node=~\"$node\", resource=\"memory\"}) by (node) / sum by(node)((machine_memory_bytes{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}))",
     "legendFormat": "{{node}} - max"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(node)((rate (container_network_receive_bytes_total{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{node}} - in"
    },
    {
     "expr": "sum by(node)((rate (container_network_transmit_bytes_total{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}[1m])))",
     "legendFormat": "{{node}} - out"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} - read"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{job=~\".*cadvisor\",cluster_name=\"$cluster_name\",node=~\"$node\"}[30s])) by (node)",
     "legendFormat": "{{node}} - write"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node)((container_fs_usage_bytes{job=~\".*cadvisor\",device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",cluster_name=\"$cluster_name\",node=~\"$node\"}))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum by(node)((container_fs_limit_bytes{job=~\".*cadvisor\",device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",cluster_name=\"$cluster_name\",node=~\"$node\"}))",
     "legendFormat": "{{node}} - max"
    }
   ]
  }
 ]
}