{
 "title": "Kubernetes Pod Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{ },cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster_name=\"$cluster_name\"}, namespace)"
    }
   },
   {
    "name": "podLabel",
    "label": "Pod Label",
    "query": {
     "query": "label_values(kube_pod_labels{cluster_name=\"$cluster_name\", namespace=~\"$namespace\"},label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{cluster_name=\"$cluster_name\", namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$podLabel\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[ Summary ] - $namespace - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(namespace)(kube_pod_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Total Container",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kube_pod_container_info{cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Total Core(Request)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max(kube_pod_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace, pod)\n  *\n  on(pod)\n  group_right(namespace)\n  sum (\n    kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",resource=\"cpu\"}\n  ) by (pod)\n)"
    }
   ]
  },
  {
   "title": "Total Memory(Request)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max(kube_pod_labels{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace, pod)\n  *\n  on(pod)\n  group_right(namespace)\n  sum (\n    kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",resource=\"memory\"}\n  ) by (pod)\n)"
    }
   ]
  },
  {
   "title": "Network In (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Network Out (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Pods Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max (kube_pod_container_info{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod,container,image)"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])) by (pod,container) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (pod,container)\n"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (pod,container)\n"
    },
    {
     "expr": "max (rate (container_network_receive_bytes_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,container,node)"
    },
    {
     "expr": "max (rate (container_network_transmit_bytes_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,container,node)"
    },
    {
     "expr": "max by (pod,container) (time() - kube_pod_created{cluster_name=\"$cluster_name\",namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Pods CPU Usage $namespace ( 1m avg )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",container!=\"\"}[1m])) by(namespace) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",resource=\"cpu\"}) by(namespace)) * 100",
     "legendFormat": "REQUEST - {{ namespace }}"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",container!=\"\"}[1m])) by(namespace) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",resource=\"cpu\"}) by(namespace)) * 100",
     "legendFormat": "LIMIT - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage $namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\"}) by(namespace) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",resource=\"memory\"}) by(namespace)",
     "legendFormat": "REQUEST - {{namespace}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\"}) by(namespace) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",resource=\"memory\"}) by(namespace)",
     "legendFormat": "LIMIT -  {{namespace}}"
    }
   ]
  },
  {
   "title": "Pods Network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} - in"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\", cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }} - out"
    }
   ]
  },
  { "title": "Pod Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])) by (pod,container) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])) by (pod,container) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (pod,container))",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "Pods CPU (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])) by (pod,container)",
     "legendFormat": "{{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\", pod=~\"$pod\",resource=\"cpu\"}) by (pod,container)",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{image!=\"\",cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}[1m])",
     "legendFormat": "{{pod}} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "Pods Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container)",
     "legendFormat": "{{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",cluster_name=\"$cluster_name\",pod=~\"$pod\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "REQUEST - {{ pod }} ~ {{ container }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster_name\",namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (pod,container)",
     "legendFormat": "LIMITS - {{ pod }} ~ {{ container }}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster_name=\"$cluster_name\",namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Container Process",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(container_processes{image!=\"\",cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container)",
     "legendFormat": "{{ pod }} ~ {{  container }}"
    }
   ]
  },
  { "title": "Anomaly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Pods Container Waiting",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod,container,reason) (kube_pod_container_status_waiting_reason{cluster_name=\"$cluster_name\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}} - {{container}}: {{reason}}"
    }
   ]
  }
 ]
}