apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loadgen
  namespace: flux-app
spec:
  chart:
    spec:
      version: 1.0.1
  values:
    image:
      tag: latest
    extraEnvVars:
      - name: SERVICE_VERSION
        value: latest
      - name: TARGET_URL
        value: http://storefront.sample-app.svc.cluster.local:3000
      - name: LOADGEN_RPS
        value: "10"
      - name: LOADGEN_CONCURRENCY
        value: "1"
      - name: LOADGEN_DURATION_SECONDS
        value: "0"
      - name: LOADGEN_CHECKOUT_RATIO
        value: "0.3"
      - name: LOADGEN_AUTOSTART
        value: "false"
    secret:
      enabled: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    loggingOperator:
      enabled: false
    secretStore:
      enabled: false
    ingress:
      enabled: false
