apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: headlamp
      version: "0.43.0"
  interval: 5m0s
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    nameOverride: "headlamp"
    fullnameOverride: "headlamp"
    replicaCount: 1

    image:
      registry: ghcr.io
      repository: headlamp-k8s/headlamp

    clusterRoleBinding:
      create: true
      clusterRoleName: cluster-admin

    serviceAccount:
      create: true
      name: headlamp

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: headlamp.annasik.cloud
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: headlamp-tls
          hosts:
            - headlamp.annasik.cloud
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/auth-url: "https://headlamp.annasik.cloud/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://headlamp.annasik.cloud/oauth2/start?rd=$scheme://$best_http_host$request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, Authorization"
    config:
      inCluster: true
      inClusterContextName: "main"
      unsafeUseServiceAccountToken: true 
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp

    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 64Mi
    #   limits:
    #     cpu: 200m
    #     memory: 256Mi