apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  values:
    image:
      tag: latest
    auth:
      username: postgres
      password: postgres
