apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: devops-mcp-server
  namespace: flux-app
spec:
  chart:
    spec:
      version: 1.0.1
  values:
    image:
      tag: latest
    extraEnvVars:
      - name: TRANSPORT
        value: "http"
      - name: NODE_ENV
        value: "prod"
      - name: PORT
        value: "3000"
      - name: MCP_TRANSPORT
        value: "http"
      - name: K8S_AUTH_MODE
        value: "incluster"
      - name: PROMETHEUS_URL
        value: "http://monitoring-prometheus-server.monitoring"
      - name: LOKI_URL
        value: "http://loki.monitoring.svc.cluster.local:3100"
      - name: MCP_AUTH_TOKEN
        value: "bIjIS4tu"
      - name: MCP_ENABLE_WRITE_TOOLS
        value: "true"
      - name: ALLOWED_REMEDIATION_NAMESPACES
        value: "dev-auth,nginx-ingress,default,monitoring,headlamp"
      - name: MAX_SCALE_DELTA
        value: "5"
      - name: TRACING_BACKEND
        value: "jaeger"
      - name: TRACING_URL
        value: "http://jaeger-query.observability.svc.cluster.local:16686"
    resources: {}
    externalSecret:
      enabled: false
