apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sarang-tani-api
  namespace: flux-app
spec:
  chart:
    spec:
      version: 1.0.1
  values:
    image:
      tag: df12549b684c1461d8f90a2762d4f361d33fb087
    extraEnvVars:
      - name: MQTT_BROKER_URL
        value: "mqtt://mqtt-broker.mqtt-broker.svc.cluster.local:1883"
      - name: MQTT_USERNAME
        value: "sarang-tani-api"
      - name: MQTT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sarang-tani-api-secret
            key: MQTT_PASSWORD
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: sarang-tani-api-secret
            key: JWT_SECRET
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: sarang-tani-api-secret
            key: MONGODB_URI
    secret:
      enabled: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    loggingOperator:
      enabled: false
    secretStore:
      enabled: false
    resources: {}
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
        ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hostname: apisarangtani.sutansolusi.com
      apiVersion: "networking.k8s.io/v1"
      pathType: Prefix
      path: /
      tls: true
      selfSigned: true
