{
 "title": "AWS SQS Dashboard",
 "tags": [
  "aws",
  "sqs",
  "prometheus",
  "cloudwatch-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue_name",
    "label": "Queue name",
    "query": {
     "query": "label_values(aws_sqs_approximate_number_of_messages_visible_sum,queue_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (Aggregated Stat per Queue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Visible (backlog)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Not Visible (in-flight)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Delayed",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Oldest Message Age",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_age_of_oldest_message_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Message Operations (Sent)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_sent_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "'{{queue_name}}' sent"
    }
   ]
  },
  {
   "title": "Message Operations (Received)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_received_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "'{{queue_name}}' received"
    }
   ]
  },
  {
   "title": "Message Operations (Deleted)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_deleted_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "'{{queue_name}}' deleted"
    }
   ]
  },
  { "title": "Other RAW metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Messages Delayed in Queue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}} delayed"
    }
   ]
  },
  {
   "title": "Status of Messages in Queue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}} delayed"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}} visible"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}} not visible"
    }
   ]
  },
  {
   "title": "Number of Empty Receive",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_number_of_empty_receives_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Sent Message Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_sqs_sent_message_size_sum{queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}