{
 "title": "AWS CNI Metrics",
 "description": "USE (Utilization Saturation Errors) metrics dashboards for troubleshooting pod IP management in EKS",
 "tags": [
  "Amazon",
  "AWS",
  "CNI",
  "EKS",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(awscni_assigned_ip_addresses{job=\"aws-cni-metrics\"}, instance)"
    }
   },
   {
    "name": "ip_deletion_reason",
    "query": {
     "query": "label_values(awscni_del_ip_req_count{job=\"aws-cni-metrics\"}, reason)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CNI Pods",
   "type": "stat",
   "description": "agents and nodes should match\n\nnormal pods + preemptible pods should match\nthe assigned ip addresses count,\nmodulo pods using the host network",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(awscni_eni_max)", "legendFormat": "Agents" },
    { "expr": "sum(kube_node_labels)", "legendFormat": "Nodes" },
    {
     "expr": "sum(kube_pod_info{priority_class!=\"overprovisioning\",created_by_name!~\"aws-node|kube-proxy|kube-prometheus-stack-prometheus-node-exporter\"})",
     "legendFormat": "Normal Pods"
    },
    {
     "expr": "sum(kube_pod_info{priority_class=\"overprovisioning\"})",
     "legendFormat": "Preemptible Pods"
    }
   ]
  },
  {
   "title": "ENI in the Cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(awscni_eni_max)", "legendFormat": "Max" },
    { "expr": "sum(awscni_eni_allocated)", "legendFormat": "Allocated" }
   ]
  },
  {
   "title": "IP Addresses in the Cluster",
   "type": "stat",
   "description": "Max: max IP addresses reachable with these nodes\n\nAssigned: IP addresses assigned to pods",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(awscni_ip_max-1)", "legendFormat": "Max" },
    {
     "expr": "sum(awscni_assigned_ip_addresses)",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Available IP Addresses in the Cluster",
   "type": "stat",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(awscni_total_ip_addresses-1-awscni_assigned_ip_addresses)",
     "legendFormat": "Warm"
    },
    {
     "expr": "sum(awscni_ip_max-awscni_total_ip_addresses)",
     "legendFormat": "Cold"
    }
   ]
  },
  {
   "title": "IP Addresses in the Cluster",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awscni_assigned_ip_addresses)",
     "legendFormat": "assigned to pods"
    },
    {
     "expr": "sum(awscni_total_ip_addresses-1)",
     "legendFormat": "total number"
    },
    { "expr": "sum(awscni_ip_max-1)", "legendFormat": "max that can be allocated" }
   ]
  },
  {
   "title": "ENI Usage (node count per usage %)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"value\", 100*awscni_eni_allocated/awscni_eni_max)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "ENI Usage (Cluster)",
   "type": "gauge",
   "description": "ENI usage on nodes",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(awscni_eni_allocated/awscni_eni_max)/count(awscni_eni_allocated)"
    }
   ]
  },
  {
   "title": "IP Addresses Usage (Cluster)",
   "type": "gauge",
   "description": "IP Addresses usage on attached ENIs",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(awscni_assigned_ip_addresses/(awscni_total_ip_addresses-1))/count(awscni_assigned_ip_addresses)"
    }
   ]
  },
  {
   "title": "Add/Del IP Address Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(awscni_add_ip_req_count[$__rate_interval]))",
     "legendFormat": "add"
    },
    {
     "expr": "sum (rate(awscni_del_ip_req_count[$__rate_interval]))",
     "legendFormat": "del"
    }
   ]
  },
  {
   "title": "Force Removed ENI / IP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(awscni_force_removed_enis)", "legendFormat": "ENI" },
    { "expr": "sum(awscni_force_removed_ips)", "legendFormat": "IP" }
   ]
  },
  {
   "title": "Delete IP Address Errors",
   "type": "stat",
   "description": "Zero is good",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (awscni_del_ip_req_count{reason!=\"PodDeleted\"})"
    }
   ]
  },
  {
   "title": "Delete IP Address Errors (by Reason)",
   "type": "timeseries",
   "description": "Zero is good",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (awscni_del_ip_req_count{reason!=\"PodDeleted\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "API Errors on the Period",
   "type": "stat",
   "description": "Zero is good",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api) (sum_over_time(awscni_aws_api_error_count[$__interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "API Errors on the Period (by API)",
   "type": "timeseries",
   "description": "Non zero means errors or IP addresses leaks",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (api) (sum_over_time(awscni_aws_api_error_count[$__interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average AWS API Latency (5min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api)(rate(awscni_aws_api_latency_ms_sum[5m])/rate(awscni_aws_api_latency_ms_count[5m]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "ipamd Actions in Progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (fn) (awscni_ipamd_action_inprogress)",
     "legendFormat": "{{fn}}"
    }
   ]
  },
  {
   "title": "The number of times ipamd reconciles on ENIs and IP addresses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(awscni_reconcile_count[5m])) by (fn)",
     "legendFormat": "{{fn}}"
    }
   ]
  },
  { "title": "CNI Metrics Per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Assigned IP Addresses",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "awscni_assigned_ip_addresses" }
   ]
  },
  {
   "title": "IP Deletion Requests (Cumulated)",
   "type": "table",
   "description": "reason=PodDeleted is normal",
   "gridPos": { "h": 11, "w": 7, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "awscni_del_ip_req_count" }
   ]
  },
  {
   "title": "API Errors (cumulated)",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "awscni_aws_api_error_count" }
   ]
  }
 ]
}