{
 "title": "HTTP Response",
 "description": "blackbox_exporter HTTP monitoring panel",
 "tags": [
  "http/https",
  "blackbox_exporter",
  "web",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(probe_http_status_code, project)"
    }
   },
   { "name": "app", "label": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{project=~\"$project\", app=~\"$app\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "HTTP Monitoring Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "title": "Detailed Information",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time()"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} * 1000"
    },
    {
     "expr": "sum(probe_http_duration_seconds{project=~\"$project\", app=~\"$app\"}) by (instance)"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{project=~\"$project\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Instance status percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)",
     "legendFormat": "Success status instance"
    },
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)",
     "legendFormat": "Failed status instance"
    }
   ]
  },
  { "title": "Response code change record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Response code change record",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}