apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ecr
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://public.ecr.aws/m6e7l0s5/main
  type: oci
  provider: aws
