apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ecr
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://476114140166.dkr.ecr.ap-southeast-1.amazonaws.com
  type: oci
  provider: aws
