apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/nvlannasik/main
  type: oci
  provider: generic
