apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nuclio
  namespace: flux-system
spec:
  interval: 24h
  url: https://nuclio.github.io/nuclio/charts
  timeout: 2m