apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sarang-tani-web
  namespace: flux-app
spec:
  chart:
    spec:
      version: 1.0.1
  values:
    image:
      tag: edb935cc83027c74434833f8543b5d862cee8c2e
    extraEnvVars:
      - name: NEXT_PUBLIC_API_URL
        value: "https://apisarangtani.sutansolusi.com"
      - name: NEXT_PUBLIC_SOCKET_URL
        value: "https://apisarangtani.sutansolusi.com"
    secret:
      enabled: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    loggingOperator:
      enabled: false
    secretStore:
      enabled: false
    resources: {}
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
        ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hostname: sarangtani.sutansolusi.com
      apiVersion: "networking.k8s.io/v1"
      pathType: Prefix
      path: /
      tls: true
      selfSigned: true
