{
 "title": "RDS Instance Overview",
 "description": "AWS RDS instance details",
 "tags": [
  "dmf",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "Account",
    "query": "label_values(rds_instance_info, aws_account_id)"
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": "label_values(rds_instance_info{aws_account_id=\"$aws_account_id\"}, aws_region)"
   },
   {
    "name": "dbidentifier",
    "label": "Instance",
    "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\", aws_region=~\"$aws_region\"}, dbidentifier)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine",
   "type": "stat",
   "description": "RDS Engine",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Engine Version",
   "type": "stat",
   "description": "RDS Engine version",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since RDS instance creation",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_instance_age_seconds{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n"
    }
   ]
  },
  {
   "title": "Instance class",
   "type": "stat",
   "description": "RDS instance class (db.<family>.<instance size>)",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "stat",
   "description": "Total number of vCPU",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    max(rds_instance_vcpu_average{}) by (instance_class)\n    * on (instance_class)\n    group_left(aws_account_id,aws_region,dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n)\n",
     "legendFormat": "Number of vCPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Total memory",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    max(rds_instance_memory_bytes{}) by (instance_class)\n    * on (instance_class)\n    group_left(dbidentifier) max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier, instance_class)\n)\n",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Allocated storage",
   "type": "stat",
   "description": "Total disk storage",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Storage type",
   "type": "stat",
   "description": "Storage class type)",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Multi AZ",
   "type": "stat",
   "description": "Multi Availability Zone deployment",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Instance role (primary or replica)",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "description": "Number of RDS instances replicating this instance",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",source_dbidentifier=\"$dbidentifier\"})\n"
    }
   ]
  },
  {
   "title": "Source database",
   "type": "stat",
   "description": "Primary instance name for a replica)",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "DBI resource ID",
   "type": "stat",
   "description": "AWS RDS instance internal reference",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "CA certificate identifier",
   "type": "stat",
   "description": "Certificate Authority bundle used by this RDS instance for TLS connections",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Snapshot retention",
   "type": "stat",
   "description": "AWS RDS snapshot retention. This is not related to AWS Backup service",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_backup_retention_period_seconds{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Current CPU usage",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Curent memory usage",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n- sum(rds_freeable_memory_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n  * 100\n  / sum(rds_instance_memory_bytes{}\n  * on (instance_class) group_left(dbidentifier) rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n)\nby (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "gauge",
   "description": "Current disk IOPS usage",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    rds_read_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n    + rds_write_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n  )\n  * 100\n  / rds_max_disk_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n)\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "description": "Current disk storage usage",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - max(\n  rds_free_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n  * 100\n  / rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "stat",
   "description": "Replication lag for replica RDS instance",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_replica_lag_seconds{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n"
    }
   ]
  },
  {
   "title": "Instance status",
   "type": "stat",
   "description": "Current RDS instance status",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_instance_status{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Pending modification",
   "type": "stat",
   "description": "Yes when RDS instance need a modification (e.g. Apply new parameter group settings). Modification could be scheduled during maintenance windows or triggered manually.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Pending maintenance",
   "type": "stat",
   "description": "AWS may required hardward or software maintenance. Maintenance could be scheduled during maintenance windows or triggered manually.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n"
    }
   ]
  },
  {
   "title": "Active queries vs vCPU",
   "type": "timeseries",
   "description": "Number of active queries waiting for CPU and non CPU wait. For optimal performances, you should not have more CPU wait that number of CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(rds_dbload_cpu_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "CPU wait"
    },
    {
     "expr": "max(rds_dbload_noncpu_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Non CPU wait"
    },
    {
     "expr": "max(\n    max(rds_instance_vcpu_average{}) by (instance_class)\n    * on (instance_class)\n    group_left(aws_account_id,aws_region,dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n)\n",
     "legendFormat": "Number of vCPU"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Ratio of CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "The number of client network connections to the database instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(rds_database_connections_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Disk IOPS usage",
   "type": "timeseries",
   "description": "Total of read and write disk IOPS regarding instance IOPS limits. For optimal performances, you should not reach IOPS limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(rds_max_disk_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Max"
    },
    {
     "expr": "max(rds_read_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Read"
    },
    {
     "expr": "max(rds_write_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The amount of available Random Access Memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n    max(rds_instance_memory_bytes{}) by (instance_class)\n    * on (instance_class)\n    group_left(dbidentifier) max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier, instance_class)\n)\n",
     "legendFormat": "Max"
    },
    {
     "expr": "max(rds_freeable_memory_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Freeable"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "description": "The average number of bytes read/write from disk per second. For optimal performances, you should not reach disk throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_read_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Read"
    },
    {
     "expr": "max(rds_write_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Write"
    },
    {
     "expr": "max(rds_max_storage_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "description": "Amount of swap space used on the DB instance. There's nothing wrong with a used SWAP, but for optimial perfomance you should avoid frequent changes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_swap_usage_bytes{dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "description": "Storage size per type. WAL only applied to PostgreSQL",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(rds_replication_slot_disk_usage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Replication slots"
    },
    {
     "expr": "max(rds_transaction_logs_disk_usage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "WAL"
    },
    {
     "expr": "max(rds_instance_log_files_size_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Logs"
    },
    {
     "expr": "max(rds_free_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "description": "RDS instance status. Some AWS operations could not be performed when instance is not in 'available' status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "max(rds_instance_status{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Used storage",
   "type": "timeseries",
   "description": "Ratio of free disk space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - max(\n  rds_free_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n  * 100\n  / rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}\n)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Used Transactions",
   "type": "timeseries",
   "description": "The number of transactions currently used. Hard limit to 2 billion transactions (See Transaction ID Wraparound)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(rds_maximum_used_transaction_ids_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "description": "Lag of PostgreSQL replica instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rds_replica_lag_seconds{}) by (dbidentifier)\n* on (dbidentifier)\ngroup_left(source_dbidentifier)\nmax(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",source_dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  { "title": "Scaling capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Regardless of the allocated disk IOPS, the EC2 instance behind RDS also has disk IOPS limits. You can't use more IOPS than EC2's instance limit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(rds_read_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n+ max(rds_write_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(rds_max_disk_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Max"
    },
    {
     "expr": "max(\n    max(rds_instance_max_iops_average{}) by (instance_class)\n    * on (instance_class)\n    group_left(aws_account_id,aws_region,dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n) by (instance_class)\n",
     "legendFormat": "Instance type limit ({{instance_class}})"
    }
   ]
  },
  {
   "title": "RDS storage autoscaling usage",
   "type": "timeseries",
   "description": "If RDS storage autoscaling is enabled, display the current usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"} * 100 / rds_max_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "description": "Regardless of the allocated disk throughput, the EC2 instance behind RDS also has disk throughput limits. You can't use more throughput than EC2's instance limit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_read_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n+ max(rds_write_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(rds_max_storage_throughput_bytes{dbidentifier=\"$dbidentifier\"})\n",
     "legendFormat": "Max"
    },
    {
     "expr": "max(\nmax(rds_instance_max_throughput_bytes{}) by (instance_class)\n* on (instance_class)\ngroup_left(aws_account_id,aws_region,dbidentifier)\nmax(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n) by (instance_class)\n",
     "legendFormat": "Instance type limit ({{instance_class}})"
    }
   ]
  }
 ]
}