apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: devops-llm-worker
  namespace: flux-app
spec:
  chart:
    spec:
      version: 1.0.1
  values:
    image:
      tag: latest
    extraEnvVars:
      - name: SQS_REQUEST_QUEUE_NAME
        value: "llm-request.fifo"
      - name: SQS_RESPONSE_QUEUE_NAME
        value: "llm-response.fifo"
      - name: SQS_REQUEST_DLQ_NAME
        value: "llm-request-dlq.fifo"
      - name: SQS_POLL_WAIT_SECONDS
        value: "20"
      - name: SQS_MAX_MESSAGES
        value: "10"
      - name: AWS_REGION
        value: "ap-southeast-1"
      - name: LLM_BASE_URL
        value: "https://api.openai.com/v1"
      - name: LLM_MODEL
        value: "gpt-5-nano-2025-08-07"
      - name: LLM_MAX_TOKENS
        value: "16384"
      - name: LLM_USE_MAX_COMPLETION_TOKENS
        value: "true"
      - name: GITOPS_REPO
        value: "nvlannasik/gitops-devops-ai-manifest"
      - name: GITHUB_API_URL
        value: "https://api.github.com"
      - name: GITOPS_BRANCH
        value: "main"
      - name: SQS_GITOPS_REQUEST_QUEUE_NAME
        value: "gitops-request.fifo"
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token-secret
            key: token
      - name: LLM_API_KEY
        valueFrom:
          secretKeyRef:
            name: llm-api-key-secret
            key: api-key
      - name: AWS_TRUST_ANCHOR_ARN
        valueFrom:
          secretKeyRef:
            name: aws-rolesanywhere-config
            key: trust-anchor-arn
      - name: AWS_ROLESANYWHERE_PROFILE_ARN
        valueFrom:
          secretKeyRef:
            name: aws-rolesanywhere-config
            key: profile-arn
      - name: AWS_ROLE_ARN
        valueFrom:
          secretKeyRef:
            name: aws-rolesanywhere-config
            key: role-arn
      - name: CERT_PATH
        value: "/certs/tls.crt"
      - name: CERT_KEY_PATH
        value: "/certs/tls.key"
    extraVolumes:
      - name: workload-cert
        secret:
          secretName: workload-tls
    extraVolumeMounts:
      - name: workload-cert
        mountPath: /certs
        readOnly: true