apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqtt-broker
  namespace: flux-system
spec:
  targetNamespace: mqtt-broker
  chart:
    spec:
      chart: mosquitto
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: mosquitto
      version: "2.4.1"
  interval: 5m0s
  install:
    remediation:
      retries: 3
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: mqtt-broker-auth
      valuesKey: passwordEntries
      targetPath: authentication.passwordEntries
  values:
    replicaCount: 1
    strategyType: Recreate
    image:
      repository: eclipse-mosquitto
    fullnameOverride: "mqtt-broker"
    nameOverride: "mqtt-broker"
    service:
      type: ClusterIP
      externalTrafficPolicy: null
      ports:
        mqtt:
          port: 1883
        websocket:
          port: 9090
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "longhorn"
      size: 2Gi
    authentication:
      passwordFilePath: "/etc/mosquitto/passwordfile"
    config: |
      persistence true
      persistence_location /mosquitto/data/
      log_dest stdout
      listener 1883
      allow_anonymous false
      password_file /etc/mosquitto/passwordfile
      listener 9090
      protocol websockets
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi