apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nuclio
  namespace: flux-system
spec:
  targetNamespace: nuclio
  chart:
    spec:
      chart: nuclio
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: nuclio
      version: "0.23.2"
  interval: 5m0s
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    controller:
      enabled: true
      image:
        repository: quay.io/nuclio/controller
    dashboard:
      enabled: true
      image:
        repository: quay.io/nuclio/dashboard
      containerBuilderKind: kaniko
      monitorDockerDeamon:
        enabled: false
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
          ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - nuclio.annasik.cloud
        tls:
          - secretName: nuclio-tls
            hosts:
              - nuclio.annasik.cloud
    autoscaler:
      enabled: true
      image:
        repository: quay.io/nuclio/autoscaler
    dlx:
      enabled: true
      image:
        repository: quay.io/nuclio/dlx
    registry:
      secretName: ghcr-creds
      pushPullUrl: ghcr.io/nvlannasik
      kind: offCluster

    platform:
      autoScaleMetricsMode: custom
      functionAugmentedConfigs:
        - labelSelector: {}
          kubernetes:
            deployment:
              spec:
                template:
                  metadata:
                    annotations:
                      prometheus.io/scrape: "true"
                      prometheus.io/port: "8090"
                      prometheus.io/path: "/metrics"
          functionConfig:
            spec:
              scaleToZero:
                scaleResources:
                  - metricName: "nuclio_processor_handled_events_total"
                    windowSize: "1m"
                    threshold: 0
      metrics:
        sinks:
          promPull:
            kind: prometheusPull
            url: :8090
        system:
          - promPull
        functions:
          - promPull
      scaleToZero:
        scalerInterval: 30s
        readinessPollInterval: 3s
        metricsClient:
          kind: prometheusClient
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local:80
          templates:
            - name: nuclio_processor_handled_events_total
              template: sum by (function) (rate(nuclio_processor_handled_events_total[5m]))